<?php

/**
 * Configuration file generated by Laminas API Tools Admin
 *
 * The previous config file has been stored in ./config/modules.config.old
 */
return [
    'Zend\\Cache',
    'Zend\\Form',
    'Laminas\\Db',
    'Laminas\\Filter',
    'Laminas\\Hydrator',
    'Laminas\\InputFilter',
    'Laminas\\Paginator',
    'Laminas\\Router',
    'Laminas\\Validator',
    'Laminas\\ApiTools',
    'Laminas\\ApiTools\\Documentation',
    'Laminas\\ApiTools\\ApiProblem',
    'Laminas\\ApiTools\\Configuration',
    'Laminas\\ApiTools\\OAuth2',
    'Laminas\\ApiTools\\MvcAuth',
    'Laminas\\ApiTools\\Hal',
    'Laminas\\ApiTools\\ContentNegotiation',
    'Laminas\\ApiTools\\ContentValidation',
    'Laminas\\ApiTools\\Rest',
    'Laminas\\ApiTools\\Rpc',
    'Laminas\\ApiTools\\Versioning',
    'Laminas\\ApiTools\\Admin',
    'DoctrineModule',
    'Phpro\\DoctrineHydrationModule',
    'Laminas\\ApiTools\\Doctrine\\Admin',
    'Laminas\\ApiTools\\Doctrine\\Server',
    'DoctrineORMModule',
    'Application',
    'DoctrineTest',
];
